[package]
name = "mono"
version = "0.0.1"
edition = "2021"

[dependencies]
glob = "0.3.0"
ignore = "0.4.18"
log = "0.4.17"
serde = { version = "1.0.147", features = ["derive"] }
serde_yaml = "0.9.14"
stderrlog = "0.5.3"
structopt = "0.3.26"
thiserror = "1.0.37"

[dev-dependencies]
maplit = "1.0.2"
